# Generated by Django 4.1.7 on 2023-06-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_competition_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
