# Generated by Django 4.1.7 on 2023-06-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_competition_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
