# Generated by Django 4.1.7 on 2023-06-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_customuser_awards_customuser_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sompetitions',
            new_name='competitions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='awards',
        ),
    ]
